# This is a basic workflow to help you get started with Actions

name: Build Latex
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build Latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
              
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          working_directory: 2023/AMATYC_J-4
          root_file: |
           main.tex
           hexagon.png 
      - run: ls -l
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf


